/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelos.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JQuery
 */
public class Menu_Movimientos extends javax.swing.JPanel {

    Usuario user;
    public Menu_Movimientos(Usuario u) {
        user = u;
        initComponents();
        panel.setViewportView(new GUIPresentacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        registrarCamarones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registrarCajas = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 1140, 500));

        registrarCamarones.setBackground(new java.awt.Color(255, 255, 255));
        registrarCamarones.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        registrarCamarones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Movimiento_Camaron.PNG"))); // NOI18N
        registrarCamarones.setText("CAMARONES");
        registrarCamarones.setBorder(null);
        registrarCamarones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCamaronesActionPerformed(evt);
            }
        });
        add(registrarCamarones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 50));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU MOVIMIENTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("INTERFAZ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("MOVIMIENTOS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Interfaz_Icon.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        registrarCajas.setBackground(new java.awt.Color(255, 255, 255));
        registrarCajas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        registrarCajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Movimiento_Caja.png"))); // NOI18N
        registrarCajas.setText("CAJAS             ");
        registrarCajas.setBorder(null);
        registrarCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCajasActionPerformed(evt);
            }
        });
        add(registrarCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void registrarCamaronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCamaronesActionPerformed
        panel.setViewportView(new Movimientos_Registrar_Camarones(user));  
    }//GEN-LAST:event_registrarCamaronesActionPerformed

    private void registrarCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCajasActionPerformed
         panel.setViewportView(new Movimientos_Registrar_Cajas(user));  
    }//GEN-LAST:event_registrarCajasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane panel;
    private javax.swing.JButton registrarCajas;
    private javax.swing.JButton registrarCamarones;
    // End of variables declaration//GEN-END:variables
}
