/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Modelos.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JQuery
 */
public class Menu_Consumo extends javax.swing.JPanel {

    Usuario user;
    public Menu_Consumo(Usuario u) {
        user = u;
        initComponents();
        panel.setViewportView(new GUIPresentacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JScrollPane();
        registrarCamarones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RegistrarCajas = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        actualizar1 = new javax.swing.JButton();
        actualizar2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 1100, 500));

        registrarCamarones.setBackground(new java.awt.Color(255, 255, 255));
        registrarCamarones.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        registrarCamarones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Consumo_Camaron.PNG"))); // NOI18N
        registrarCamarones.setText("CAMARONES");
        registrarCamarones.setBorder(null);
        registrarCamarones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCamaronesActionPerformed(evt);
            }
        });
        add(registrarCamarones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, 50));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU CONSUMO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("INTERFAZ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("CONSUMO");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Interfaz_Icon.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        RegistrarCajas.setBackground(new java.awt.Color(255, 255, 255));
        RegistrarCajas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RegistrarCajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/Consumo_Caja.png"))); // NOI18N
        RegistrarCajas.setText("CAJAS         ");
        RegistrarCajas.setBorder(null);
        RegistrarCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCajasActionPerformed(evt);
            }
        });
        add(RegistrarCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 50));

        consultar.setBackground(new java.awt.Color(255, 255, 255));
        consultar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/venta_Consultar.png"))); // NOI18N
        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 50));

        actualizar.setBackground(new java.awt.Color(255, 255, 255));
        actualizar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/venta_cancelar.png"))); // NOI18N
        actualizar.setText("ANULAR      ");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 50));

        actualizar1.setBackground(new java.awt.Color(255, 255, 255));
        actualizar1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        actualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/unidad_Actualizar.png"))); // NOI18N
        actualizar1.setText("EDITAR CAMARONES");
        actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar1ActionPerformed(evt);
            }
        });
        add(actualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 50));

        actualizar2.setBackground(new java.awt.Color(255, 255, 255));
        actualizar2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        actualizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Img/unidad_Actualizar.png"))); // NOI18N
        actualizar2.setText("EDITAR CAJAS");
        actualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar2ActionPerformed(evt);
            }
        });
        add(actualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void registrarCamaronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCamaronesActionPerformed
        panel.setViewportView(new ConsumoCamarones_Registrar_BodNacional(user));
    }//GEN-LAST:event_registrarCamaronesActionPerformed

    private void RegistrarCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCajasActionPerformed
        panel.setViewportView(new ConsumoCajas_Registrar_BodNacional(user));
    }//GEN-LAST:event_RegistrarCajasActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        try {
            panel.setViewportView(new Consumo_Consultar());
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Consumo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try {
            panel.setViewportView(new Consumo_Anular(user));
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Consumo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar1ActionPerformed
        panel.setViewportView(new ConsumoCamarones_Editar_BodNacional(user));
    }//GEN-LAST:event_actualizar1ActionPerformed

    private void actualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar2ActionPerformed
         panel.setViewportView(new ConsumoCajas_Editar_BodNacional(user));
    }//GEN-LAST:event_actualizar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistrarCajas;
    private javax.swing.JButton actualizar;
    private javax.swing.JButton actualizar1;
    private javax.swing.JButton actualizar2;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane panel;
    private javax.swing.JButton registrarCamarones;
    // End of variables declaration//GEN-END:variables
}
